Repository MichalLytek/type-graphql, pull requests merged in 2019-11, with the labels that each got.

#369 Directives support with `@Directive` decorator
  CHANGELOG.md
  docs/directives.md
  package-lock.json
  src/decorators/Directive.ts
  src/decorators/index.ts
  src/errors/InvalidDirectiveError.ts
  src/errors/index.ts
  src/interfaces/ResolverInterface.ts
  src/metadata/definitions/class-metadata.ts
  src/metadata/definitions/directive-metadata.ts
  src/metadata/definitions/field-metadata.ts
  src/metadata/definitions/index.ts
  src/metadata/definitions/resolver-metadata.ts
  src/metadata/metadata-storage.ts
  src/schema/definition-node.ts
  src/schema/schema-generator.ts
  tests/functional/directives.ts
  tests/helpers/directives/AppendDirective.ts
  tests/helpers/directives/UpperCaseDirective.ts
  tests/helpers/directives/assertValidDirective.ts
  website/i18n/en.json
  website/sidebars.json
Labels: Community :family_man_girl:, Enhancement :new:

#462 Fix transforming and validating nested inputs and arrays
  CHANGELOG.md
  docs/validation.md
  src/helpers/types.ts
  src/resolvers/convert-args.ts
  src/resolvers/helpers.ts
  src/resolvers/validate-arg.ts
  src/schema/schema-generator.ts
  tests/functional/resolvers.ts
  tests/functional/validation.ts
Labels: Bugfix :bug: :hammer:

#465 Sort emitted schema SDL file
  CHANGELOG.md
  docs/emit-schema.md
  examples/generic-types/schema.gql
  examples/interfaces-inheritance/schema.gql
  examples/mixin-classes/schema.gql
  examples/simple-usage/schema.gql
  examples/typegoose/schema.gql
  src/utils/buildSchema.ts
  src/utils/emitSchemaDefinitionFile.ts
  src/utils/index.ts
  tests/functional/emit-schema-sdl.ts
Labels: Enhancement :new:

#473 Upgraded browser shim
  docs/browser-usage.md
  gulpfile.ts
  src/browser-shim.ts
Labels: Enhancement :new:
