Repository MichalLytek/type-graphql, pull requests merged in 2019-03, with the labels that each got.

#271 Fix a typo in getting-started.md
  docs/getting-started.md
  website/versioned_docs/version-0.16.0/getting-started.md
  website/versioned_docs/version-0.17.0/getting-started.md
Labels: Community :family_man_girl:, Documentation :book:

#269 feat(emit-schema): add support for recursive directory creation
  CHANGELOG.md
  package-lock.json
  package.json
  src/helpers/filesystem.ts
  src/utils/buildSchema.ts
  src/utils/emitSchemaDefinitionFile.ts
  tests/functional/emit-schema-sdl.ts
Labels: Community :family_man_girl:, Enhancement :new:

#276 Add types field at package.json, because we do not use default value
  CHANGELOG.md
  package.json
Labels: Bug :bug:, Community :family_man_girl:

#279 fix(inheritance): allow for returning plain objects
  CHANGELOG.md
  docs/generic-types.md
  examples/generic-types/recipe.resolver.ts
  src/errors/InterfaceResolveTypeError.ts
  src/errors/index.ts
  src/schema/schema-generator.ts
  tests/functional/generic-types.ts
  tests/functional/interfaces-and-inheritance.ts
Labels: Bug :bug:
