Repository MichalLytek/type-graphql, pull requests merged in 2020-01, with the labels that each got.

#488 Optimize resolvers execution paths
  CHANGELOG.md
  benchmarks/array/graphql-js/async.ts
  benchmarks/array/graphql-js/standard.ts
  benchmarks/array/results.txt
  benchmarks/array/run.ts
  benchmarks/array/type-graphql/async-field-resolvers.ts
  benchmarks/array/type-graphql/simple-resolvers.ts
  benchmarks/array/type-graphql/standard.ts
  benchmarks/array/type-graphql/sync-field-resolvers.ts
  benchmarks/array/type-graphql/sync-getters.ts
  benchmarks/array/type-graphql/with-global-middleware.ts
  docs/performance.md
  src/resolvers/create.ts
  src/resolvers/helpers.ts
  src/utils/isPromiseLike.ts
Labels: Community :family_man_girl:, Discussion :speech_balloon:, Enhancement :new:

#499 Fix duplicated entries for resolver classes that use inheritance
  CHANGELOG.md
  src/metadata/metadata-storage.ts
  src/metadata/utils.ts
  tests/functional/metadata-storage.ts
Labels: Community :family_man_girl:, Discussion :speech_balloon:, Out of scope :heavy_multiplication_x:

#520 Update bootstrap docs
  docs/bootstrap.md
  website/versioned_docs/version-0.17.1/bootstrap.md
Labels: Community :family_man_girl:, Documentation :book:

#521 Add @Extensions decorator
  CHANGELOG.md
  dev.js
  docs/extensions.md
  examples/extensions/context.interface.ts
  examples/extensions/examples.gql
  examples/extensions/helpers/config.extractors.ts
  examples/extensions/helpers/recipe.ts
  examples/extensions/index.ts
  examples/extensions/log-message.decorator.ts
  examples/extensions/logger.middleware.ts
  examples/extensions/logger.service.ts
  examples/extensions/recipe.type.ts
  examples/extensions/resolver.ts
  examples/extensions/user.interface.ts
  src/decorators/Extensions.ts
  src/decorators/index.ts
  src/metadata/definitions/class-metadata.ts
  src/metadata/definitions/extensions-metadata.ts
  src/metadata/definitions/field-metadata.ts
  src/metadata/definitions/index.ts
  src/metadata/definitions/resolver-metadata.ts
  src/metadata/metadata-storage.ts
  src/metadata/utils.ts
  src/schema/schema-generator.ts
  tests/functional/extensions.ts
  website/i18n/en.json
  website/sidebars.json
Labels: Community :family_man_girl:, Enhancement :new:
