Repository MichalLytek/type-graphql, pull requests merged in 2020-03, with the labels that each got.

#567 Fix interface resolvers with custom schemaName
  CHANGELOG.md
  src/schema/schema-generator.ts
  tests/functional/interfaces-and-inheritance.ts
Labels: Community :family_man_girl:, Enhancement :new:

#578 Fix `@Authorized` in subscriptions
  CHANGELOG.md
  src/resolvers/create.ts
  src/schema/schema-generator.ts
  tests/functional/subscriptions.ts
Labels: Bug :bug:

#579 Defining arguments and implementing resolvers for interface types fields
  CHANGELOG.md
  docs/interfaces.md
  examples/interfaces-inheritance/person/person.interface.ts
  examples/interfaces-inheritance/person/person.type.ts
  src/decorators/types.ts
  src/metadata/metadata-storage.ts
  src/schema/schema-generator.ts
  tests/functional/interface-resolvers-args.ts
Labels: Enhancement :new:
