Repository MichalLytek/type-graphql, pull requests merged in 2024-01, with the labels that each got.

#1578 Migrate subscriptions engine to graphql-yoga
  CHANGELOG.md
  docs/migration-guide.md
  docs/subscriptions.md
  examples/redis-subscriptions/comment.type.ts
  examples/redis-subscriptions/index.ts
  examples/redis-subscriptions/pubsub.ts
  examples/redis-subscriptions/recipe.resolver.ts
  examples/redis-subscriptions/topics.ts
  examples/simple-subscriptions/examples.graphql
  examples/simple-subscriptions/index.ts
  examples/simple-subscriptions/notification.resolver.ts
  examples/simple-subscriptions/notification.type.ts
  examples/simple-subscriptions/pubsub.ts
  examples/simple-subscriptions/resolver.ts
  examples/simple-subscriptions/schema.graphql
  package-lock.json
  package.json
  src/decorators/PubSub.ts
  src/decorators/Subscription.ts
  src/decorators/index.ts
  src/decorators/types.ts
  src/errors/MissingPubSubError.ts
  src/errors/index.ts
  src/index.ts
  src/metadata/definitions/resolver-metadata.ts
  src/resolvers/create.ts
  src/resolvers/helpers.ts
  src/schema/build-context.ts
  src/schema/schema-generator.ts
  src/shim.ts
  src/typings/Publisher.ts
  src/typings/ResolverTopicData.ts
  src/typings/SubscribeResolverData.ts
  src/typings/SubscriptionHandlerData.ts
  src/typings/index.ts
  src/typings/subscriptions.ts
  tests/functional/directives.ts
  tests/functional/metadata-storage.ts
  tests/functional/query-complexity.ts
  tests/functional/resolvers.ts
  tests/functional/subscriptions.ts
  tests/functional/typedefs-resolvers.ts
  website/i18n/en.json
  website/sidebars.json
Labels: Enhancement :new:

#1284 fix: use schemaName instead of methodName when building field resolve…
  src/metadata/metadata-storage.ts
  tests/functional/resolvers.ts
Labels: Community :family_man_girl:, Need More Info :man_shrugging:, Bugfix :bug: :hammer:

#1597 fix:(ci): workflows that depends on another workflow
  .github/workflows/check.yml
  .github/workflows/license.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
Labels: Chore :hammer:, Bugfix :bug: :hammer:

#1309 fix(resolvers): resolve #1142 name issue and add relevant tests
  src/utils/createResolversMap.ts
  tests/functional/typedefs-resolvers.ts
Labels: Community :family_man_girl:, Bugfix :bug: :hammer:

#1608 Apollo Cache example: Allow maxAge to be 0
  examples/apollo-cache/cache-control.ts
Labels: Community :family_man_girl:, Documentation :book:

#1611 build: remove support for node 16
  .npmrc
  package.json
Labels: Community :family_man_girl:, Chore :hammer:
